// Mock campaigns
export const MOCK_CAMPAIGNS = [
  {
    id: "campaign-1",
    name: "Beauty Q1 2026",
    persona: "Beauty and skincare micro-influencers targeting Gen Z audiences, focused on clean beauty and sustainable products",
    owner_id: "mock-user",
    created_at: "2026-02-15T10:00:00Z",
  },
  {
    id: "campaign-2",
    name: "Fitness Summer Push",
    persona: "Fitness and wellness creators who post workout routines, meal prep, and healthy lifestyle content",
    owner_id: "mock-user",
    created_at: "2026-03-01T10:00:00Z",
  },
  {
    id: "campaign-3",
    name: "Tech Gadgets Review",
    persona: "Tech reviewers and gadget unboxers with engaged audiences interested in consumer electronics",
    owner_id: "mock-user",
    created_at: "2026-03-10T10:00:00Z",
  },
]

// Mock creators for discover tab
export const MOCK_CREATORS = [
  {
    id: "creator-1",
    campaign_creator_id: "cc-1",
    handle: "glowwithsara",
    profile_url: "https://www.tiktok.com/@glowwithsara",
    cover_url: "https://picsum.photos/seed/sara/400/225",
    followers: 45200,
    avg_views: 12300,
    bio: "Clean beauty advocate | Skincare routines that actually work | PR: sara@glow.co",
    bio_link: "https://linktr.ee/glowwithsara",
    emails: ["sara@glow.co"],
    tier: "micro",
    status: "approved" as const,
    source_type: "search" as const,
    source_keyword: "clean beauty routine",
    source_handle: null,
    nickname: "Sara Glow",
    country_code: "US",
    total_likes: 1200000,
    video_count: 187,
    following_count: 342,
    verified: false,
    engagement_rate: 0.065,
    median_views: 11800,
    tcm_id: null,
    tcm_link: null,
    batch_id: "batch-1",
  },
  {
    id: "creator-2",
    campaign_creator_id: "cc-2",
    handle: "skinbylee",
    profile_url: "https://www.tiktok.com/@skinbylee",
    cover_url: "https://picsum.photos/seed/lee/400/225",
    followers: 128000,
    avg_views: 34500,
    bio: "Dermatologist-approved skincare tips | NYC",
    bio_link: "https://skinbylee.com",
    emails: ["contact@skinbylee.com", "lee@gmail.com"],
    tier: "mid",
    status: "approved" as const,
    source_type: "search" as const,
    source_keyword: "skincare tips",
    source_handle: null,
    nickname: "Lee Skin",
    country_code: "US",
    total_likes: 4800000,
    video_count: 245,
    following_count: 189,
    verified: false,
    engagement_rate: 0.042,
    median_views: 32100,
    tcm_id: null,
    tcm_link: null,
    batch_id: "batch-1",
  },
  {
    id: "creator-3",
    campaign_creator_id: "cc-3",
    handle: "beautybymai",
    profile_url: "https://www.tiktok.com/@beautybymai",
    cover_url: "https://picsum.photos/seed/mai/400/225",
    followers: 22100,
    avg_views: 8700,
    bio: "Makeup tutorials & honest reviews",
    bio_link: null,
    emails: [],
    tier: "micro",
    status: "unreviewed" as const,
    source_type: "search" as const,
    source_keyword: "makeup tutorial",
    source_handle: null,
    nickname: "Mai Beauty",
    country_code: "GB",
    total_likes: 580000,
    video_count: 92,
    following_count: 215,
    verified: false,
    engagement_rate: 0.058,
    median_views: 8200,
    tcm_id: null,
    tcm_link: null,
    batch_id: "batch-1",
  },
  {
    id: "creator-4",
    campaign_creator_id: "cc-4",
    handle: "naturalvibes.co",
    profile_url: "https://www.tiktok.com/@naturalvibes.co",
    cover_url: "https://picsum.photos/seed/vibes/400/225",
    followers: 67400,
    avg_views: 15200,
    bio: "Sustainable beauty | Eco-friendly finds | collab: hello@naturalvibes.co",
    bio_link: "https://naturalvibes.co",
    emails: ["hello@naturalvibes.co"],
    tier: "micro",
    status: "unreviewed" as const,
    source_type: "similar" as const,
    source_keyword: null,
    source_handle: "glowwithsara",
    nickname: "Natural Vibes",
    country_code: "CA",
    total_likes: 2100000,
    video_count: 156,
    following_count: 278,
    verified: false,
    engagement_rate: 0.048,
    median_views: 14500,
    tcm_id: null,
    tcm_link: null,
    batch_id: "batch-2",
  },
  {
    id: "creator-5",
    campaign_creator_id: "cc-5",
    handle: "jennas.glow",
    profile_url: "https://www.tiktok.com/@jennas.glow",
    cover_url: "https://picsum.photos/seed/jenna/400/225",
    followers: 9800,
    avg_views: 3200,
    bio: "Glow-up journey | before & after | DM for collabs",
    bio_link: null,
    emails: [],
    tier: "nano",
    status: "rejected" as const,
    source_type: "search" as const,
    source_keyword: "glow up transformation",
    source_handle: null,
    nickname: "Jenna Glow",
    country_code: "US",
    total_likes: 195000,
    video_count: 64,
    following_count: 412,
    verified: false,
    engagement_rate: 0.074,
    median_views: 2900,
    tcm_id: null,
    tcm_link: null,
    batch_id: "batch-1",
  },
  {
    id: "creator-6",
    campaign_creator_id: "cc-6",
    handle: "skincaredaily_",
    profile_url: "https://www.tiktok.com/@skincaredaily_",
    cover_url: "https://picsum.photos/seed/daily/400/225",
    followers: 312000,
    avg_views: 89000,
    bio: "Your daily dose of skincare science | PhD in Biochem",
    bio_link: "https://skincaredaily.shop",
    emails: ["pr@skincaredaily.shop"],
    tier: "macro",
    status: "approved" as const,
    source_type: "search" as const,
    source_keyword: "skincare science",
    source_handle: null,
    nickname: "Skincare Daily",
    country_code: "US",
    total_likes: 15600000,
    video_count: 298,
    following_count: 127,
    verified: false,
    engagement_rate: 0.035,
    median_views: 85000,
    tcm_id: null,
    tcm_link: null,
    batch_id: "batch-1",
  },
  {
    id: "creator-7",
    campaign_creator_id: "cc-7",
    handle: "glossyrita",
    profile_url: "https://www.tiktok.com/@glossyrita",
    cover_url: null,
    followers: 18500,
    avg_views: 6100,
    bio: "Lip gloss queen | affordable beauty",
    bio_link: null,
    emails: ["rita.beauty@gmail.com"],
    tier: "micro",
    status: "unreviewed" as const,
    source_type: "search" as const,
    source_keyword: "affordable beauty haul",
    source_handle: null,
    nickname: "Glossy Rita",
    country_code: "GB",
    total_likes: 420000,
    video_count: 78,
    following_count: 165,
    verified: false,
    engagement_rate: 0.061,
    median_views: 5800,
    tcm_id: null,
    tcm_link: null,
    batch_id: "batch-1",
  },
  {
    id: "creator-8",
    campaign_creator_id: "cc-8",
    handle: "dewydani",
    profile_url: "https://www.tiktok.com/@dewydani",
    cover_url: "https://picsum.photos/seed/dani/400/225",
    followers: 54000,
    avg_views: 17800,
    bio: "Glass skin enthusiast | K-beauty lover | biz: dani@dewyskin.com",
    bio_link: "https://dewyskin.com",
    emails: ["dani@dewyskin.com"],
    tier: "micro",
    status: "unreviewed" as const,
    source_type: "similar" as const,
    source_keyword: null,
    source_handle: "skinbylee",
    nickname: "Dewy Dani",
    country_code: "US",
    total_likes: 1750000,
    video_count: 134,
    following_count: 203,
    verified: false,
    engagement_rate: 0.053,
    median_views: 16900,
    tcm_id: null,
    tcm_link: null,
    batch_id: "batch-2",
  },
]

// Mock keywords
export const MOCK_KEYWORDS = [
  { id: "kw-1", keyword: "clean beauty routine", source: "manual" as const, created_at: "2026-02-16T10:00:00Z" },
  { id: "kw-2", keyword: "skincare tips", source: "manual" as const, created_at: "2026-02-16T11:00:00Z" },
  { id: "kw-3", keyword: "makeup tutorial", source: "ai" as const, created_at: "2026-02-17T10:00:00Z" },
  { id: "kw-4", keyword: "glow up transformation", source: "ai" as const, created_at: "2026-02-18T10:00:00Z" },
  { id: "kw-5", keyword: "affordable beauty haul", source: "ai" as const, created_at: "2026-02-18T11:00:00Z" },
  { id: "kw-6", keyword: "skincare science", source: "manual" as const, created_at: "2026-02-19T10:00:00Z" },
  { id: "kw-7", keyword: "K-beauty glass skin", source: "ai" as const, created_at: "2026-02-20T10:00:00Z" },
]

// Mock outreach creators (approved with emails)
export const MOCK_OUTREACH_CREATORS = [
  { creator_id: "creator-1", handle: "glowwithsara", emails: ["sara@glow.co"] },
  { creator_id: "creator-2", handle: "skinbylee", emails: ["contact@skinbylee.com"] },
  { creator_id: "creator-6", handle: "skincaredaily_", emails: ["pr@skincaredaily.shop"] },
]

// Mock outreach log
export const MOCK_OUTREACH_LOG = [
  {
    id: "ol-1",
    email: "sara@glow.co",
    subject: "Collab opportunity — Beauty Q1 Campaign",
    status: "sent",
    error: null,
    sent_at: "2026-03-10T14:30:00Z",
    creator: { handle: "glowwithsara" },
    note: "Very responsive, interested in long-term collab",
    note_tag: "interested",
  },
  {
    id: "ol-2",
    email: "contact@skinbylee.com",
    subject: "Collab opportunity — Beauty Q1 Campaign",
    status: "sent",
    error: null,
    sent_at: "2026-03-10T14:30:05Z",
    creator: { handle: "skinbylee" },
    note: null,
    note_tag: null,
  },
  {
    id: "ol-3",
    email: "pr@skincaredaily.shop",
    subject: "Collab opportunity — Beauty Q1 Campaign",
    status: "failed",
    error: "SMTP connection timeout",
    sent_at: null,
    creator: { handle: "skincaredaily_" },
    note: null,
    note_tag: "bounced",
  },
]

// Mock presets
export const MOCK_PRESETS = [
  {
    id: "preset-1",
    campaign_id: "campaign-1",
    name: "Micro-KOL",
    is_default: true,
    filters: {
      followers: { min: 5000, max: 100000 },
      avg_views: { min: 1000, max: null },
      engagement_rate: { min: 0.02, max: null },
    },
    created_at: "2026-02-15T10:00:00Z",
    updated_at: "2026-02-15T10:00:00Z",
  },
  {
    id: "preset-2",
    campaign_id: "campaign-1",
    name: "Mid-Tier",
    is_default: false,
    filters: {
      followers: { min: 50000, max: 500000 },
      avg_views: { min: 10000, max: null },
    },
    created_at: "2026-02-15T10:00:00Z",
    updated_at: "2026-02-15T10:00:00Z",
  },
]

// Mock batches
export const MOCK_BATCHES = [
  {
    id: "batch-1",
    campaign_id: "campaign-1",
    source_type: "keyword_creator" as const,
    source_params: { keywords: ["clean beauty routine", "skincare tips"], country: "US", sort_by: "follower" },
    preset_id: "preset-1",
    preset_snapshot: { followers: { min: 5000, max: 100000 }, avg_views: { min: 1000, max: null }, engagement_rate: { min: 0.02, max: null } },
    task_id: "task-2",
    creator_count: 6,
    created_at: "2026-03-15T10:00:00Z",
  },
  {
    id: "batch-2",
    campaign_id: "campaign-1",
    source_type: "similar" as const,
    source_params: { creator_id: "creator-1", creator_handle: "glowwithsara" },
    preset_id: "preset-1",
    preset_snapshot: { followers: { min: 5000, max: 100000 } },
    task_id: "task-3",
    creator_count: 2,
    created_at: "2026-03-16T10:00:00Z",
  },
  {
    id: "batch-3",
    campaign_id: "campaign-1",
    source_type: "keyword_video" as const,
    source_params: { keywords: ["glow up transformation"] },
    preset_id: null,
    preset_snapshot: null,
    task_id: "task-1",
    creator_count: 0,
    created_at: "2026-03-17T09:00:00Z",
  },
  {
    id: "batch-4",
    campaign_id: "campaign-1",
    source_type: "keyword_creator" as const,
    source_params: { keywords: ["tech gadgets review"] },
    preset_id: "preset-1",
    preset_snapshot: { followers: { min: 5000, max: 100000 } },
    task_id: "task-4",
    creator_count: 0,
    created_at: "2026-03-17T08:00:00Z",
  },
]

// Mock tasks
export const MOCK_TASKS = [
  {
    id: "task-1",
    user_id: "mock-user",
    type: "scout",
    status: "running" as const,
    meta: { source_type: "keyword_video", source_params: { keywords: ["glow up transformation"] } },
    progress: 14,
    total: 20,
    error: null,
    created_at: "2026-03-17T09:00:00Z",
    updated_at: "2026-03-17T09:02:30Z",
  },
  {
    id: "task-2",
    user_id: "mock-user",
    type: "scout",
    status: "completed" as const,
    meta: { source_type: "keyword_creator", source_params: { keywords: ["clean beauty routine", "skincare tips"] }, result_count: 6 },
    progress: 20,
    total: 20,
    error: null,
    created_at: "2026-03-15T08:45:00Z",
    updated_at: "2026-03-15T08:50:00Z",
  },
  {
    id: "task-3",
    user_id: "mock-user",
    type: "scout",
    status: "completed" as const,
    meta: { source_type: "similar", source_params: { creator_id: "creator-1", creator_handle: "@glowwithsara" }, result_count: 2 },
    progress: 5,
    total: 5,
    error: null,
    created_at: "2026-03-16T08:30:00Z",
    updated_at: "2026-03-16T08:32:00Z",
  },
  {
    id: "task-4",
    user_id: "mock-user",
    type: "scout",
    status: "failed" as const,
    meta: { source_type: "keyword_creator", source_params: { keywords: ["tech gadgets review"] } },
    progress: 3,
    total: 20,
    error: "TikHub API timeout",
    created_at: "2026-03-17T08:00:00Z",
    updated_at: "2026-03-17T08:05:00Z",
  },
]
